-- AUTOGENERATED FILE (from genramvhd.c run on -w) --
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package demo_bin_pkg is
  type t_word_array is array(natural range <>) of std_logic_vector(63 downto 0);
  constant demo_bin : t_word_array(10 downto 0) := (
     0 => x"00000f9300000793",  1 => x"0000093700020737",
     2 => x"ffc70713000009b7",  3 => x"0589899305890913",
     4 => x"0009202301390863",  5 => x"ff394ce300490913",
     6 => x"0000006f008000ef",  7 => x"31f9089300002937",
     8 => x"3379091397990813",  9 => x"0018889303180833",
    10 => x"00008067ff289ce3");
end demo_bin_pkg;
