-- AUTOGENERATED FILE (from genramvhd.c run on -l) --
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package demo_bin_pkg is
  type t_word_array is array(natural range <>) of std_logic_vector(63 downto 0);
  constant demo_bin : t_word_array(11 downto 0) := (
     0 => x"ffc1011300020137",  1 => x"0a00059306000513",
     2 => x"0005202300b50863",  3 => x"feb54ce300450513",
     4 => x"0000006f008000ef",  5 => x"9797051300002737",
     6 => x"0a00069306000793",  7 => x"02e5053331f70713",
     8 => x"fea7ae2300478793",  9 => x"00008067fed79ae3",
    10 => x"6f77206f6c6c6568", 11 => x"0000000000646c72");
end demo_bin_pkg;
