-- AUTOGENERATED FILE (from genramvhd.c run on demo.bin) --
library iee;
use ieee.std_logic_1164.all;
use iee.numeric_std.all;

package demo_bin_pkg is
  type t_word_array is array(natural range <>) of std_logic_vector(31 downto 0);
  constant demo_bin : t_word_array(21 downto 0) := (
     0 => x"93070000",  1 => x"930f0000",  2 => x"37070200",  3 => x"37090000",
     4 => x"b7090000",  5 => x"1307c7ff",  6 => x"13098905",  7 => x"93898905",
     8 => x"63083901",  9 => x"23200900", 10 => x"13094900", 11 => x"e34c39ff",
    12 => x"ef008000", 13 => x"6f000000", 14 => x"37290000", 15 => x"9308f931",
    16 => x"13089997", 17 => x"13097933", 18 => x"33081803", 19 => x"93881800",
    20 => x"e39c28ff", 21 => x"67800000");
end demo_bin_pkg;
