-- AUTOGENERATED FILE (from genramvhd.c run on riscv.bin) --
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package demo_pkg is
  type t_word_array is array(natural range <>) of std_logic_vector(31 downto 0);
  constant demo : t_word_array(32767 downto 0) := (
        0 => x"00020137",     1 => x"ffc10113",     2 => x"0e000513",
        3 => x"1b000593",     4 => x"00b50e63",     5 => x"00000013",
        6 => x"00000013",     7 => x"00000013",     8 => x"00052023",
        9 => x"00450513",    10 => x"feb54ce3",    11 => x"014000ef",
       12 => x"0000006f",    13 => x"00000000",    14 => x"00000000",
       15 => x"00000000",    16 => x"00200293",    17 => x"00000513",
       18 => x"0b000393",    19 => x"0d000313",    20 => x"01000893",
       21 => x"00038613",    22 => x"00030593",    23 => x"00000693",
       24 => x"0005c783",    25 => x"00061703",    26 => x"00260613",
       27 => x"00d79833",    28 => x"02f707b3",    29 => x"00168693",
       30 => x"00158593",    31 => x"010787b3",    32 => x"00f50533",
       33 => x"fea61f23",    34 => x"fd169ce3",    35 => x"fff28293",
       36 => x"fc0292e3",    37 => x"00008067",    38 => x"00000000",
       39 => x"00000000",    40 => x"6c6c6568",    41 => x"6f77206f",
       42 => x"00646c72",    43 => x"00000000",    44 => x"ffff0000",
       45 => x"fffd0002",    46 => x"fffb0004",    47 => x"fff90006",
       48 => x"fff70008",    49 => x"fff5000a",    50 => x"fff3000c",
       51 => x"fff1000e",    52 => x"fdfe0100",    53 => x"f9fa0504",
       54 => x"f5f60908",    55 => x"f1f20d0c", others => (others => '0'));
end demo_pkg;
